#!/bin/bash

# Update Git submodules
git submodule update --init

# Install Python packages using pip
pip install flask flask_cors bs4 lxml pelican markdown gevent

# Optionally, yopip install flask flask_cors bs4 lxml pelican markdown geventu can add more commands or customizations here.